"%prod":
  kafka:
    bootstrap:
      servers: "kafka:9092"

quarkus:
  swagger-ui:
    always-include: true
  kafka:
    devservices:
      topic-partitions:
        test: 1
        test-acknowledged: 1

mp:
  messaging:
    outgoing:
      test-out:
        topic: "test"
      test-acknowledged-out:
        topic: "test-acknowledged"
    incoming:
      test-in:
        topic: "test"
