name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-publish-build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn -B test --file pom.xml

      - name: Semantic Release
        if: ${{ github.event_name == 'push' }}
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-release
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
        env:
          persist-credentials: false
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build with Maven
        if: ${{ (github.event_name == 'push') && (steps.semantic-release.outputs.new_release_published == 'true') }}
        run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx
        if: ${{ (github.event_name == 'push') && (steps.semantic-release.outputs.new_release_published == 'true') }}
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: ${{ (github.event_name == 'push') && (steps.semantic-release.outputs.new_release_published == 'true') }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        run: |
          echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Build and push Docker image
        if: ${{ (github.event_name == 'push') && (steps.semantic-release.outputs.new_release_published == 'true') }}
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./src/main/docker/Dockerfile.jvm
          tags: ghcr.io/${REPO_LOWERCASE}:${{ steps.semantic-release.outputs.new_release_version }}
